# Site settings
title: Jeremy Berchtold
description: Jeremy Berchtold's Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jeremy Berchtold
user_description: Jeremy Berchtold portfolio. Software Developer. Computer Science. California Polytechnic State University San Luis Obispo 2021.
user_title: Software Developer - Cal Poly SLO 2021

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
